### ISSUE TITLE
NBT tags do not apply with Shift+Click

### ISSUE THREAD

**Issue by MJRamon** [SattesKrokodil/runetech_theory#4]
When crafting ring, NBT tags are applied only when you pick result with cursor, but when you press Shift+Click on craft result, they are not added.

**Comment by MJRamon** [comment]
Looks like using `NbtCompound nbtRing = stack.getOrCreateNbt();` instead of `NbtCompound nbtRing = new NbtCompound();` and removing `stack.setNbt(nbtRing);` fixes the issue.
I can be wrong.

**Comment by SattesKrokodil** [comment]
thank you I will try that!
